name: amd64_windows_clang

on:
  push:
  pull_request:
  workflow_dispatch: # Enables manual run from GitHub UI

jobs:
  amd64_windows_clang:
    runs-on: windows-2019
    env:
      CC: clang
      CXX: clang++

    steps:
      - uses: actions/checkout@v2

      - name: Add MSYS2 to PATH
        run: echo "C:\\msys64\\usr\\bin" >> $GITHUB_PATH

      - name: Pacman version
        run: pacman --version

      - name: Update mirrors
        run: |
          pacman -Sy
          pacman --noconfirm -S pacman-mirrors

      - name: Install dependencies
        run: |
          pacman --noconfirm -S \
            mingw64/mingw-w64-x86_64-clang \
            mingw64/mingw-w64-x86_64-cmake \
            mingw64/mingw-w64-x86_64-qtwebkit \
            mingw64/mingw-w64-x86_64-python2

      - name: Add MinGW to PATH
        run: echo "C:\\msys64\\mingw64\\bin" >> $GITHUB_PATH

      - name: Display tools version
        run: |
          clang++ --version
          cmake --version
          qmake --version

      - name: Configure
        run: bash ./configure
        env:
          CMAKE_CMD: 'cmake -G "MinGW Makefiles"'

      - name: Build
        run: mingw32-make

      - name: Show binary info
        run: |
          file ./bin/phantomjs
          ldd ./bin/phantomjs
          ./bin/phantomjs --version

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: phantomjs-windows
          path: ./bin/phantomjs
